### ISSUE TITLE
how is keyfactorCommunityRA.p12 generated from EJBCA GUI?

### ISSUE THREAD

**Issue by kaitaklam** [Keyfactor/keyfactorcommunity#1]
Just need to know how to generate keyfactorCommunityRA.p12 from EJBCA GUI.
It would be great if you provide some hints.
Because I got error: curl: (60) Peer's certificate issuer has been marked as not trusted by the user.

I user the SuperAdmin.p12

**Comment by kaitaklam** [comment]
Invoke:
./pkcs10Enroll.sh -c server.csr  -P SuperAdmin.p12  -s foo123 -t ManagementCA.pem  -H ejbca-node1 -p "TLS Server Profile" -e "TLS Server Profile" -n MyPKISubCA-G1 -u server

I got this error. 
{"error_code":403,"error_message":"Error no client certificate or OAuth token received for authentication."}

**Comment by svenska-primekey** [comment]
> Invoke: ./pkcs10Enroll.sh -c server.csr -P SuperAdmin.p12 -s foo123 -t ManagementCA.pem -H ejbca-node1 -p "TLS Server Profile" -e "TLS Server Profile" -n MyPKISubCA-G1 -u server
> 
> I got this error. {"error_code":403,"error_message":"Error no client certificate or OAuth token received for authentication."}

Did the EJBCA logs container anything? seems like the p12 credential is not being sent up with the curl command.

**Comment by kaitaklam** [comment]
The problem is with my old curl version that doesn't send the client-cert. I have built teh latest curl version and now it is working. But I got an error:
{"error_code":403,"error_message":"Administrator is not authorized to resource /administrator. Msg: ."}

I have tried to create several certs from RA web and run the curl, all with the same error_code.
Looks like I am missing adding some Administration permission. No idea where to find.
(I will be on leave for 2 weeks, so my reply will be after 2 weeks)
--trace---
curl   -X POST -vvv --cacert ManagementCA.pem --cert-type P12 --cert RAAdministrator.p12:foo123 -H 'Content-Type: application/json' --data '{
  "certificate_request": "-----BEGIN CERTIFICATE REQUEST-----\nMIIC5TCCAc0CAQAwVDELMAkGA1UEBhMCU0UxHjAcBgNVBAoMFVByaW1lS2V5IFNv\nbHV0aW9ucyBBQjEOMAwGA1UECwwFSW5mcmExFTATBgNVBAMMDHByaW1la2V5LmNv\nbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ03o7m+MBxtyYkmvZj\nsrASbn+xtCBnWFK3cAMRE+uDRZpUeU5pUNgEE7Ed5VbDLcigG1rxIFxa6b/akLzO\nXK8TXafhBZpBxev6x0CpRSrVm8/QS7v9cD8U6kJIIGCwqTJ5I1Cxvf5xAGLQf7AJ\n42Z3TrxVZKWPEwqZKgr4pd/yZSlYvLWPHu25LZeYEMh4T1vdxQFSxVwdgeas67HQ\nyG4uVWc0mfrvtJfx9QMaVtP9cY8xSVh2av9+xd6JDu8cQHw4X3RzR2/MJrY34pxF\n6/OavD4Mr2aFdC7SqkZmbwfb3xWXxPbP1+G97LVo1aC4BJrbUZUhrbilMFwPK3gf\ne+8CAwEAAaBMMEoGCSqGSIb3DQEJDjE9MDswCwYDVR0PBAQDAgWgMBMGA1UdJQQM\nMAoGCCsGAQUFBwMBMBcGA1UdEQQQMA6CDHByaW1la2V5LmNvbTANBgkqhkiG9w0B\nAQsFAAOCAQEAsQyRaf79Ur9eU1n5QYpx7gH08h4ixnLAkAMXSPlkZtF6aHvv+neD\nBNEJ/+wQulghWfjuDJXgSwzd4Uoz1cXbXi16mXfOovqO/HdxQwvByoPg6rVTvskf\nv8iY0pYGZEGSo7iFM7xDPIbcNqISG6ZYSF+BtsctdoNL+QDrkwEsX3zbNJAW4T5p\nroW+jDJOoeX2iNa4de7sxk3rOvMq4R/9VPg6IqtYu/KdQkVTCqXRzbEprrcgnJi2\nwuNJSi6/VW82rhK8HXZpYGoT0MAtZ+9Jz8ropZsgrcBjzYWLRqTuG7NaLPoG7e+f\nblfDqg04Of/oxz2Bq2zwnzqjouRpxIRQgQ==\n-----END CERTIFICATE REQUEST-----",
  "certificate_profile_name": "TLS Server Profile",
  "end_entity_profile_name": "TLS Server Profile",
  "certificate_authority_name": "MyPKISubCA-G1",
  "username": "server",
  "password": "foo123"
}' https://ejbca-node1/ejbca/ejbca-rest-api/v1/certificate/pkcs10enroll
Note: Unnecessary use of -X or --request, POST is already inferred.
* processing: https://ejbca-node1/ejbca/ejbca-rest-api/v1/certificate/pkcs10enroll
* Uses proxy env variable no_proxy == 'localhost,127.0.0.1,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,.intinfra.com,cz.intinfra.com'
*   Trying 127.0.0.1:443...
* Connected to ejbca-node1 (127.0.0.1) port 443
* ALPN: offers http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
*  CAfile: ManagementCA.pem
*  CApath: none
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: UID=c-0uyt79oq9c2fldb3z; CN=ejbca-node1; O=EJBCA Container Quickstart
*  start date: Jul 17 12:14:54 2023 GMT
*  expire date: Jul 16 12:05:32 2025 GMT
*  subjectAltName: host "ejbca-node1" matched cert's "ejbca-node1"
*  issuer: UID=c-0uyt79oq9c2fldb3z; CN=ManagementCA; O=EJBCA Container Quickstart
*  SSL certificate verify ok.
* using HTTP/1.x
> POST /ejbca/ejbca-rest-api/v1/certificate/pkcs10enroll HTTP/1.1
> Host: ejbca-node1
> User-Agent: curl/8.2.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 1329
>
< HTTP/1.1 403 Forbidden
< X-XSS-Protection: 1
< X-Frame-Options: SAMEORIGIN
< Content-Security-Policy: default-src https:
< Date: Thu, 20 Jul 2023 13:24:17 GMT
< Connection: keep-alive
< X-Content-Type-Options: nosniff
< Strict-Transport-Security: max-age=31536000
< Content-Type: application/json
< Content-Length: 103
<
* Connection #0 to host ejbca-node1 left intact
{"error_code":403,"error_message":"Administrator is not authorized to resource /administrator. Msg: ."}

**Comment by svenska-primekey** [comment]
> The problem is with my old curl version that doesn't send the client-cert. I have built teh latest curl version and now it is working. But I got an error: {"error_code":403,"error_message":"Administrator is not authorized to resource /administrator. Msg: ."}
> 
> I have tried to create several certs from RA web and run the curl, all with the same error_code. Looks like I am missing adding some Administration permission. No idea where to find. (I will be on leave for 2 weeks, so my reply will be after 2 weeks) --trace--- curl -X POST -vvv --cacert ManagementCA.pem --cert-type P12 --cert RAAdministrator.p12:foo123 -H 'Content-Type: application/json' --data '{ "certificate_request": "-----BEGIN CERTIFICATE REQUEST-----\nMIIC5TCCAc0CAQAwVDELMAkGA1UEBhMCU0UxHjAcBgNVBAoMFVByaW1lS2V5IFNv\nbHV0aW9ucyBBQjEOMAwGA1UECwwFSW5mcmExFTATBgNVBAMMDHByaW1la2V5LmNv\nbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ03o7m+MBxtyYkmvZj\nsrASbn+xtCBnWFK3cAMRE+uDRZpUeU5pUNgEE7Ed5VbDLcigG1rxIFxa6b/akLzO\nXK8TXafhBZpBxev6x0CpRSrVm8/QS7v9cD8U6kJIIGCwqTJ5I1Cxvf5xAGLQf7AJ\n42Z3TrxVZKWPEwqZKgr4pd/yZSlYvLWPHu25LZeYEMh4T1vdxQFSxVwdgeas67HQ\nyG4uVWc0mfrvtJfx9QMaVtP9cY8xSVh2av9+xd6JDu8cQHw4X3RzR2/MJrY34pxF\n6/OavD4Mr2aFdC7SqkZmbwfb3xWXxPbP1+G97LVo1aC4BJrbUZUhrbilMFwPK3gf\ne+8CAwEAAaBMMEoGCSqGSIb3DQEJDjE9MDswCwYDVR0PBAQDAgWgMBMGA1UdJQQM\nMAoGCCsGAQUFBwMBMBcGA1UdEQQQMA6CDHByaW1la2V5LmNvbTANBgkqhkiG9w0B\nAQsFAAOCAQEAsQyRaf79Ur9eU1n5QYpx7gH08h4ixnLAkAMXSPlkZtF6aHvv+neD\nBNEJ/+wQulghWfjuDJXgSwzd4Uoz1cXbXi16mXfOovqO/HdxQwvByoPg6rVTvskf\nv8iY0pYGZEGSo7iFM7xDPIbcNqISG6ZYSF+BtsctdoNL+QDrkwEsX3zbNJAW4T5p\nroW+jDJOoeX2iNa4de7sxk3rOvMq4R/9VPg6IqtYu/KdQkVTCqXRzbEprrcgnJi2\nwuNJSi6/VW82rhK8HXZpYGoT0MAtZ+9Jz8ropZsgrcBjzYWLRqTuG7NaLPoG7e+f\nblfDqg04Of/oxz2Bq2zwnzqjouRpxIRQgQ==\n-----END CERTIFICATE REQUEST-----", "certificate_profile_name": "TLS Server Profile", "end_entity_profile_name": "TLS Server Profile", "certificate_authority_name": "MyPKISubCA-G1", "username": "server", "password": "foo123" }' https://ejbca-node1/ejbca/ejbca-rest-api/v1/certificate/pkcs10enroll Note: Unnecessary use of -X or --request, POST is already inferred.
> 
>     * processing: https://ejbca-node1/ejbca/ejbca-rest-api/v1/certificate/pkcs10enroll
> 
>     * Uses proxy env variable no_proxy == 'localhost,127.0.0.1,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,.intinfra.com,cz.intinfra.com'
> 
>     * Trying 127.0.0.1:443...
> 
>     * Connected to ejbca-node1 (127.0.0.1) port 443
> 
>     * ALPN: offers http/1.1
> 
>     * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@strength
> 
>     * TLSv1.2 (OUT), TLS handshake, Client hello (1):
> 
>     * CAfile: ManagementCA.pem
> 
>     * CApath: none
> 
>     * TLSv1.2 (IN), TLS handshake, Server hello (2):
> 
>     * TLSv1.2 (IN), TLS handshake, Certificate (11):
> 
>     * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> 
>     * TLSv1.2 (IN), TLS handshake, Request CERT (13):
> 
>     * TLSv1.2 (IN), TLS handshake, Server finished (14):
> 
>     * TLSv1.2 (OUT), TLS handshake, Certificate (11):
> 
>     * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> 
>     * TLSv1.2 (OUT), TLS handshake, CERT verify (15):
> 
>     * TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
> 
>     * TLSv1.2 (OUT), TLS handshake, Finished (20):
> 
>     * TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
> 
>     * TLSv1.2 (IN), TLS handshake, Finished (20):
> 
>     * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
> 
>     * ALPN: server did not agree on a protocol. Uses default.
> 
>     * Server certificate:
> 
>     * subject: UID=c-0uyt79oq9c2fldb3z; CN=ejbca-node1; O=EJBCA Container Quickstart
> 
>     * start date: Jul 17 12:14:54 2023 GMT
> 
>     * expire date: Jul 16 12:05:32 2025 GMT
> 
>     * subjectAltName: host "ejbca-node1" matched cert's "ejbca-node1"
> 
>     * issuer: UID=c-0uyt79oq9c2fldb3z; CN=ManagementCA; O=EJBCA Container Quickstart
> 
>     * SSL certificate verify ok.
> 
>     * using HTTP/1.x
> 
> 
> > POST /ejbca/ejbca-rest-api/v1/certificate/pkcs10enroll HTTP/1.1
> > Host: ejbca-node1
> > User-Agent: curl/8.2.0
> > Accept: _/_
> > Content-Type: application/json
> > Content-Length: 1329
> 
> < HTTP/1.1 403 Forbidden < X-XSS-Protection: 1 < X-Frame-Options: SAMEORIGIN < Content-Security-Policy: default-src https: < Date: Thu, 20 Jul 2023 13:24:17 GMT < Connection: keep-alive < X-Content-Type-Options: nosniff < Strict-Transport-Security: max-age=31536000 < Content-Type: application/json < Content-Length: 103 <
> 
>     * Connection #0 to host ejbca-node1 left intact
>       {"error_code":403,"error_message":"Administrator is not authorized to resource /administrator. Msg: ."}

You need to update the role being used and all the administrator endpoint in the role. It's the second row in the Role Based Access Rules section when viewing the role in advanced mode. Set that to allow and try again.
